name: Conditional workflow

on:
  push:
    branches:
      - main

jobs:
  conditional-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run the job if branch is main
        if: github.ref == 'refs/heads/main'
        run: echo "this workflow only run when branch is main"
