name: Conditional workflow

on:
  push:
    branches:
      - main

jobs:
  conditional-job:
    runs-on: ubuntu-latest
eps:
  - name: Acess the job value
    run: |
      echo "this value is access from job-output: ${{ needs.job-output-create.outputs.date_version}}"
