name: External Trigger

on:
  repository_dispatch:
    types:
      - deploy-request

jobs:
  external-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Show deployment request
        run: |
          echo "External deployment request received!"
          echo "Environment: ${{ github.event.client_payload.environment }}"
