name: Main Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_test:
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      run_tests: true

  docker:
    needs: build_test
    uses: ./.github/workflows/reusable-docker.yml
    with:
      image_name: alank8scloud/flask-app
      docker_username: ${{ vars.DOCKER_USERNAME }}
    secrets: inherit

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy Image
        run: |
          echo "Docker job output:"
          echo "${{ needs.docker.outputs.image_url }}"

          echo "Deploying image: ${{ needs.docker.outputs.image_url }} to production"
