name: Pull request Demo

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Unit test
        run: echo "Running test...."

      - name: system info
        run: |
          echo "HI everyone"
          echo "Current data: $(date)"
      - name: PR check for running branch
        run: |
          echo "PR check running for branch: ${{github.head_ref}}"
