# Name shown in GitHub Actions
name: Reusable Build & Test

# This workflow can be called by another workflow
on:
  workflow_call:
    # Inputs received from the calling workflow
    inputs:
      # Python version to install
      python_version:
        description: "Python version to use"
        required: false
        type: string
        default: "3.14"

      # Whether tests should be executed
      run_tests:
        description: "Whether to run tests"
        required: false
        type: boolean
        default: true

    # Outputs returned to the calling workflow
    outputs:
      test_result:
        description: "Result of the tests"
        value: ${{ jobs.build_test.outputs.test_result }}

# Jobs
jobs:
  build_test:
    runs-on: ubuntu-latest

    # Output from this job
    outputs:
      test_result: ${{ steps.test_result.outputs.test_result }}

    steps:
      # 1. Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v6

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python_version }}

      # 3. Upgrade pip
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # 4. Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install -r flask-app-ecs/requirements.txt
          echo "Dependencies installed successfully"

      # 5. Run tests
      - name: Run Tests
        if: ${{ inputs.run_tests }}
        run: |
          python -m pytest  flask-app-ecs/test_app.py

      # 6. Set test result
      - name: Set Test Result
        id: test_result
        if: always()
        run: |
          if [ "${{ inputs.run_tests }}" = "false" ]; then
            echo "test_result=passed" >> "$GITHUB_OUTPUT"
          elif [ "${{ steps.run_tests.outcome }}" = "success" ]; then
            echo "test_result=passed" >> "$GITHUB_OUTPUT"
          else
            echo "test_result=failed" >> "$GITHUB_OUTPUT"
          fi
