name: Workflow Run by External APi

on:
  repository_dispatch:
    types:
      - software-deploy

jobs:
  external-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Basic information
        run: |
          echo "current working directory: $(pwd)"
          echo "Hi everyone" > greet.txt
          echo "Show the message: $(cat greet.txt)"

      - name: Show deployment request
        run: |
          echo "External deployment request received!"
          echo "Environment: ${{ github.event.client_payload.environment }}"

      - name: Successfully run the workflow by external
        run: echo "Successfully run this workflow"
