name: Self-Hosted Runner

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the Environment to Deploy app on the Self-Hosted Runner"
        required: true
        type: choice
        options:
          - Test
          - Deploy

jobs:
  Self-Hosted:
    runs-on: [self-hosted, my-linux-runner]
    steps:
      - name: Some task
        run: |
          echo "Running on self-hosted runner"
          echo "The hostname of machine: $(hostname)"
          echo "The Working directory: $(pwd)"
           # echo "---Create file name hello.txt---"
           # touch hello.txt
           # echo "File is created successfully: $(ls -l hello.txt)"
