name: Environment variable workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment do you want to deploy"
        required: true
        type: choice
        options:
          - dev
          - staging
          - production
env:
  APP_NAME: my-app

jobs:
  env-job:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: staging
    steps:
      - name: show workflow and job variables
        run: |
          echo "App_Name: $APP_NAME"
          echo "ENVIRONMENT: $ENVIRONMENT"

      - name: Show step variable
        env:
          VERSION: 1.0.0
        run: |
          echo "VERSION: $VERSION"

      - name: show Github context
        run: |
          echo "Commit SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
