name: Run Python Test

on: workflow_dispatch

jobs:
  Python-code:
    runs-on: Ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Setup python with version 3.12
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependency flake8
        run: |
          python3 -m pip install --upgrade pip 
          pip install flake8 && pip install bandit

      - name: Lint Python code
        run: flake8 scripts/health_check.py

      - name: Scan the project
        run: bandit -r scripts/security_test.py

      - name: Run python script
        run: python3 scripts/health_check.py
