name: Upload log

on: workflow_dispatch

jobs:
  artifact:
    runs-on: Ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Generate the log files
        run: |
          echo "Workflow started" > app.log
          echo "Checking application..." >> app.log
          echo "Application check completed" >> app.log

      - name: Show log
        run: cat app.log

      - name: Upload log
        uses: actions/upload-artifact@v4
        with:
          name: workflow-logs
          path: app.log
